### ISSUE TITLE
Confusing error message when altering the type of "data"

### ISSUE THREAD

**Issue by a2aaron** [rust-fuzz/cargo-fuzz#137]
When using writing a fuzz target, one can change the signature of `data` from `&[u8]` to something else, which does not work, but prints a confusing error message.
Example:
```
fuzz_target!(|data: &[usize]| {
    // stuff
}
```

In all cases, the error message printed is 
```
error[E0463]: can't find crate for `arbitrary`
 --> fuzz/fuzz_targets/fuzz_target_1.rs:5:1
  |
5 | / fuzz_target!(|data: &[u16]| {
6 | |     // stuff
7 | | });
  | |___^ can't find crate
  |
  = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
```

This seems rather confusing, as it isn't clear that the change to the type is the reason for the missing crate.

Note that I am on `cargo 0.24.0-nightly (abd137ad1 2017-11-12)` and using `cargo-fuzz 0.5.0` on Mac OS X.

**Comment by nagisa** [comment]
Sorry this error is confusing, but it says exactly what the problem is. It is necessary to specify the dependency on `arbitrary` crate in your `Cargo.toml` to use arguments other than `&[u8]`. An example fuzz target using the `arbitrary` support is available [here](https://github.com/rust-fuzz/libfuzzer-sys/tree/master/example_arbitrary). The list of types supported by arbitrary can be seen in the "Implementors" list [here](https://docs.rs/arbitrary/0.1.0/arbitrary/trait.Arbitrary.html).

That being said, be aware that using arbitrary types can make program flow more opaque to the fuzzer and thus fuzzing take longer than if you converted the data yourself in a more naive way.

**Comment by nagisa** [comment]
Note that by default `arbitrary` crate is not an included dependency specifically because most fuzz targets do not need this support and they just convert the data naively.

**Comment by a2aaron** [comment]
Ah, I see, thank you for pointing me in the right direction!
