### ISSUE TITLE
Sanitizer coverage options can slow down binaries up to 50x

### ISSUE THREAD

**Issue by alexcrichton** [rust-fuzz/cargo-fuzz#216]
Recently we've added the `wasmtime` project to OSS fuzz and we've gotten a lot of bugs (yay!). Some of the bugs are related to timeouts and when investigating locally I was surprised that running un-fuzzed code was orders of magnitude faster than the fuzzed code so it seemed that simply fuzzing caused code to get so slow it would time out (but we saw reasonable performance on the same tests outside of fuzzing).

One big chunk of the slowdown is in https://github.com/rust-fuzz/cargo-fuzz/pull/215, but it looks like the various sanitizer coverage options are also a source of quite a large slowdown.

I ran some tests locally and was executing a command like so:

```
$ cargo +nightly run --release --target x86_64-unknown-linux-gnu --bin differential ./the-test-file
```

Basically I was curious to just run the fuzzer binary on one particular test case, timing how long it took. I varied `RUSTFLAGS` according to below and got the following timings. Note that each of these has `-Ccodegen-units=1` to account for https://github.com/rust-fuzz/cargo-fuzz/pull/215.

| `RUSTFLAGS` | test time |
|---------------|-------------|
| (empty) | 89ms |
| sancov level 1 | 385ms  |
| sancov level 4 | 428ms |
| sancov level 4 + `-sanitizer-coverage-pc-table` | 353ms |
| sancov level 4 + `-sanitizer-coverage-prune-blocks=0` | 506ms |
| sancov level 4 + `-sanitizer-coverage-trace-geps` | 1708ms |
| sancov level 4 + `-sanitizer-coverage-trace-compares` | 2327ms |
| sancov level 4 + all options | 4113ms |

Note there that "sancov level 1" corresponds to `-Cpasses=sancov -Cllvm-args=-sanitizer-coverage-level=1 -Cllvm-args=-sanitizer-coverage-inline-8bit-counters`  and "sancov level 4" correspond to `level=4` there. The default in `cargo fuzz` right now is sancov level 4. Also note that the last row above, "sancov level 4 + all options", is the default for `cargo fuzz` today.

What I largely want to highlight here is that cranking up the sancov level and options causes the slowdown of a binary to get quite large to the point that a timeout on a fuzzer may not be too relevant if it's executing up to 50x slower than it would otherwise. This leads me to a few questions:

* What are these sancov options and why are they passed by default? Do they improve libfuzzer's discovery of test cases?
* Why are all these options passed? Or, in other words, how was this list of options selected to get passed? Are we matching `clang` or just trying to pass as many options as possible?
* Would it make sense to make these options configurable? If they were configurable is there a reasonable subset that should be used all the time, or are there some projects that only want to use some?
* How beneficial is each option individually? It looks like options like `trace-compares` are extremely expensive, similar with `trace-geps`. Should those be turned off by default for everything other than "let's create a big corpus" runs or something like that?

I saw that many of these options were tweaked in https://github.com/rust-fuzz/cargo-fuzz/commit/7a31745ab02f9bc9958c2c9e189b9b169938fc3f, and I'd be curious to see how the options in `cargo fuzz` compare to whatever `clang` defaults to nowadays, for example.

**Comment by nagisa** [comment]
> What are these sancov options and why are they passed by default? Do they improve libfuzzer's discovery of test cases?

Originally libfuzzer *required* at least level 3 and an arbitrary sprinkling of these options to even do anything – otherwise it would just keep randomly generating inputs and hardly hit any panics. While I haven’t read the code, I presume that libfuzzer does indeed use this information to make more informed decisions on how to mutate input. At least used to… I don’t know about now, but I suspect it is still the case.

> Why are all these options passed? Or, in other words, how was this list of options selected to get passed? Are we matching clang or just trying to pass as many options as possible?

clang used to enable most of these LLVM flags/passes indeed and its how I came up with the initial list of the flags (level 3 + some sanitization options), but that (again) was multiple years ago and I haven’t looked into it since the project started. As you discovered yourself, @PaulGrandperrin did some investigation more recently and I’m inclined to trust their call.

---

Ultimately this will be a tradeoff between whether more targeted inputs yield better results than trying more different inputs. My experience is that better inputs produce more cases faster, but I wouldn’t be surprised if there’s a project for which unique crashers are produced faster by just trying more cases.

**Comment by alexcrichton** [comment]
Hm ok, so it's *certain* that all of these flags are necessary to produce better coverage of test cases? And it's been confirmed, at least at some point, that this is how C/C++ work and such?

I'm a little surprised that it's expected that fuzzing takes at least a 50x hit in performance, that seems egregiously large for still having tests that time out if they take too long?

**Comment by nagisa** [comment]
> it's certain that all of these flags are necessary to produce better coverage of test cases?

I think it is a stretch to call it _certain_. We definitely _not_ do any quantitative tests. 50x hit in performance is also super curious – this is not the experience I had so far but then we mostly fuzz very self-contained portions of the codebases (e.g. parser, decoder, etc.) rather than the whole project (last time _I_ tried it with rustc I ran out of memory within minutes).

**Comment by alexcrichton** [comment]
I believe so!
