### ISSUE TITLE
entry point for fuzzer to emit a testcase from the seed

### ISSUE THREAD

**Issue by nlewycky** [rust-fuzz/cargo-fuzz#259]
It's common practice to write the fuzzer in a way that uses the fuzz input as a seed into a smith library that produces the actual test input. Supporting this is why the fuzzers support any type that impl's Arbitrary.

I'd like a way to run my fuzzer in a mode where it converts one seed into the testcase. For example, "cargo fuzz generate_testcase my_fuzzer /path/to/seed -o /path/to/testcase".

**Comment by fitzgen** [comment]
Do you want the output to be the raw bits of the `T: Arbitrary`'s memory representation? Note that that isn't stable unless the `T` is `repr(C)`.

Or do you want the `Debug` formatting of the `T: Arbitrary`? That can be had via `cargo fuzz fmt <seed>`.

Or do you want the `Display`/`ToString` of the `T: Arbitrary`? We don't currently have anything that does this, but I could imagine adding a `--display` flag to `cargo fuzz fmt` or something like that. However, I'm not sure how we would actually implement it, since `Arbitrary: Debug` but not `Arbitrary: Display`.

Or do you want the serde/bincode/json/etc serialized version? Not sure that this would really make sense in a general purpose tool like `cargo fuzz` and this runs into the same issues about implementation that `Display` does.

However, writing your own little script (or checking if, say, the `DUMP_TEST_CASE` env var is set in your fuzz target) to do this would be easy since you don't have to work with any general `T: Arbitrary` but your own concrete input type.

**Comment by nlewycky** [comment]
I was picturing something along the lines of:

```
fuzz_generate_testcase!(|module: wasm_smith::ConfiguredModule<ExportedFunctionConfig>, output: &mut Vec<u8>| {
    let mut module = module;
    module.ensure_termination(100000);
    *output = module.to_bytes();
}

fuzz_target!(|module: wasm_smith::ConfiguredModule<ExportedFunctionConfig>| {
  /* ... */
}
```

framing it as two separate entry points. (While I realize that we -- well, you in particular -- could simply modify wasm_smith such that all necessary configuration information is included in `T`, I think that allowing general code in the fuzzer to do it is the right approach. The fuzzer may have any arbitrary amount of setup or configuration, reading environment variables, who knows, and the smither library may not be as well designed as wasm_smith!)

Here's what I'm doing today:

```
fuzz_target!(|module: wasm_smith::ConfiguredModule<ExportedFunctionConfig>| {
    let mut module = module;
    module.ensure_termination(100000);
    let wasm_bytes = module.to_bytes();

    use std::fs::File;
    use std::io::Write;
    let mut file = File::create("/tmp/crash.wasm").unwrap();
    file.write_all(&wasm_bytes).unwrap();

    /* ... */
```

Note that just making ConfiguredModule Debug or Display isn't sufficient because I need to run some configuration (`ensure_termination(100000);`) in order to dump the correct thing.

I could also just wrap my dumping code with `DUMP_TEST_CASE` which is ultimately fine by me, what I've been doing so far is modifying my fuzzer to add those 4 lines of code after each crash. While that environment variable solves my problem today, it'd be helpful to have some standard way to do this, where cargo fuzz knows what environment variable to set and the fuzzer knows where to put the bytes (stdout)?

**Comment by fitzgen** [comment]
I see.

As you mention, the "dump the test case" logic is going to be pretty specific to each fuzz target / input type. So it there isn't a one-size-fits-all solution, meaning we would need a customizable hook with default functionality, like the `fuzz_generate_testcase!` macro you sketched. However, I'm not sure how we could actually implement that custom hook without either trait specialization or weak symbols, neither of which are really available to us here.

You don't want to unconditionally do file I/O in your fuzz target, as that will kill fuzzing throughput.

There are two specific things you can do, however:

1. Wrap `wasm_smith::Module` in a new type that dumps the `wat` disassembly as its `std::fmt::Debug` and then use `cargo fuzz fmt`

2. Check whether logging is enabled (or if an env var is set) and only then dump the test case, eg https://github.com/bytecodealliance/wasmtime/blob/db65fa80e0e935e633394af4a5e1c87e44567f84/crates/fuzzing/src/oracles.rs#L28-L45

**Comment by nlewycky** [comment]
Wait, `cargo fuzz fmt` is _exactly_ what I want. I just had an older version of cargo-fuzz (0.5.4) which didn't have that yet!

Wrapping the wasm_smith Module and adding a Debug that calls wasmprinter works perfectly. Thank you!
