### ISSUE TITLE
Arbitrary<'_>` is not implemented for `&dyn SomeTrait`

### ISSUE THREAD

**Issue by darakian** [rust-fuzz/cargo-fuzz#319]
Hey all,

First off many thanks for the work on cargo fuzz! So, I'm running through some [Structure aware fuzzing](https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html) and attempting to have cargo fuzz generate arbitrary structs of the (simplified) form
```
struct MyStruct<'a> {
    some_option: Option<&'a dyn SomeTrait>
}
```
The trait itself has the (simplified) form 
```
pub trait SomeTrait {
    fn fun1(&self, SomeStr: Option<&str>, code: &str) -> String;

    fn fun2(&self, SomeKV: &HashMap<String, String>) -> String;

    fn fun3(&self, SomeKV: &HashMap<String, String>) -> String;
}
```

Adding the magical incantation `#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]` above the struct definition starts throwing trait bound errors ala
```
error[E0277]: the trait bound `&dyn SomeTrait: Arbitrary<'_>` is not satisfied
    |
480 | #[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
    |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `Arbitrary<'_>` is not implemented for `&dyn SomeTrait`
    |
```

I'm a bit confused as to where to go from here. I've poked around enough to find that the `Arbitrary` trait doesn't like being made `dyn`
```
480 | trait ArbitrarySomeTrait: SomeTrait + arbitrary::Arbitrary {}
    |       ---------------------------------                             ^^^^^^^^^^^^^^^^^^^^ ...because it requires `Self: Sized`
    |       |
    |       this trait cannot be made into an object...
```
but it's unclear to me how to progress or if I'm hitting a wall. Is there something I'm missing?

**Comment by Manishearth** [comment]
It's not theoretically possible to autoimplement Arbitrary for trait objects; Arbitrary is about constructing an arbitrary instance of that object from scratch.

For trait objects you'd need a registry of all possible types in that object (not available in rust, also potentially infinitely-sized. definitely infinitely-sized if you start talking about all _potential_ implementations of the trait instead of just all _currently extant_ implementations). On top of that, each concrete type would also have to impl Arbitrary, so you really need `dyn SomeTrait + Arbitrary` (which Rust won't allow, so you need to instead make it `trait SomeTrait: Arbitrary`)

You can, however, write a manual implementation that selects between a list of concrete objects that you decide. An easy way to do this is define an enum of all the concrete objects that implement your trait (that you care about), slap `#[derive(Arbitrary)]` on that, give it a method that covnerts it to a trait object, and then `impl Arbitrary for Box<dyn SomeTrait>` that goes through the enum.


(implementing Arbitrary for a _reference_ to a `dyn` is impossible, it'll have to be owned, you can take a reference in your fuzz code)

**Comment by darakian** [comment]
> For trait objects you'd need a registry of all possible types in that object (not available in rust, also potentially infinitely-sized. definitely infinitely-sized if you start talking about all potential implementations of the trait instead of just all currently extant implementations).

Gotcha. Ya that seems maybe a little hard to do :)

Is there anything written on fuzzing strategies when using cargo fuzz? The docs seem a little anemic at the moment.

**Comment by Manishearth** [comment]
There's the fuzzing book (https://rust-fuzz.github.io/book/) but that's about it.

**Comment by darakian** [comment]
Dang. Well, thank you :)
