### ISSUE TITLE
Run with detect_odr_violations=0

### ISSUE THREAD

**Issue by Manishearth** [rust-fuzz/cargo-fuzz#7]
Probably should turn off most of the asan checks. I needed `ASAN_OPTIONS=detect_odr_violation=0` to make it work on rust-url, otherwise it would bail very early.

**Comment by nagisa** [comment]
It's possible to use weaker/other sanitisers as well. AddressSanitizer is
the most aggressive of them all AFAIK

**Comment by ner0x652** [comment]
@nagisa @Manishearth what do you think if we control ASAN by it flags to diminish its aggressiveness?
https://github.com/google/sanitizers/wiki/AddressSanitizerFlags

**Comment by Manishearth** [comment]
That's the point of this bug.

**Comment by nagisa** [comment]
So now that I’m back home and have a proper keyboard… I feel like it is a much better idea to just use a different sanitizer by default *instead* of ASAN. I picked ASAN in the initial example just because it is the most aggressive sanitizer out there, but depending on the fuzzing goals, a different sanitizer, such as TSAN, MSAN or some other may be more appropriate.

We should work on providing an option to switch that *first* and pass sanitizer options later.

**Comment by Manishearth** [comment]
works for me.

**Comment by nagisa** [comment]
So, I’ve tried multiple sanitizers recently, and IIRC ASAN works the best of them all, actually. TSAN freaks out for pretty much anything even if you only use one thread (something something signal unsafe stuff); Either of LSAN/MSAN doesn’t work at all and the other is just subset of ASAN functionality. 

While it still sounds like an okay idea to allow picking out the desired sanitizer, we probably should focus our effort on supporting ASAN only.

**Comment by Manishearth** [comment]
Cool. In that case can we run by default with detect_odr_violations=0? Lots of crates seem to need that (might be a bug actually, but it doesn't look like one)

**Comment by nagisa** [comment]
Yes, sure.
